- name: "Install node.js v13"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_10.x | sudo -E bash -

- name: "Install PM2"
  npm:
    name: pm2
    global: yes
    state: present    