---

- name: "create BE directory" 
  file:
    path: ~/backend-dir
    state: directory    

- name: "unarchive BE" 
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-dir
    
- name: "install deps"
  shell: |
    cd ~/backend-dir
    npm i

- name: "Execute node with pm2"
  shell: |
    cd ~/backend-dir/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node 

- name: "Configure pm2"
  become: true
  shell: |
    env PATH=$PATH:/user/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu

  
    